;/*FB_PKG_DELIM*/

__d("InlineFbtResult",["cr:1183579"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:1183579")}),98);
__d("InlineFbtResultImplComet",["FbtHooks","FbtReactUtil","FbtResultBase","react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function k(a){var b=a.content,d=a.hash,e=a.inlineMode;a=a.translation;d==null&&c("recoverableViolation")('Fbt string hash should not be null for translated string "'+a+'" '+("[inlineMode="+e+"]"),"internationalization");return j.jsx("span",{"data-intl-hash":d,"data-intl-translation":a,"data-intl-trid":"",children:b})}k.displayName=k.name+" [from "+f.id+"]";a=function(a){babelHelpers.inheritsLoose(b,a);function b(b,e,f,g){var i;i=a.call(this,b,(h||(h=c("FbtHooks"))).getErrorListener({hash:g,translation:f}))||this;i.$$typeof=d("FbtReactUtil").REACT_ELEMENT_TYPE;i.key=null;i.ref=null;i.type=k;i.props={content:b,hash:g,inlineMode:e,translation:f};return i}return b}(c("FbtResultBase"));g["default"]=a}),98);
__d("TransAppInlineMode",[],(function(a,b,c,d,e,f){a=Object.freeze({STRING_MANAGER:"STRING_MANAGER",TRANSLATION:"TRANSLATION",APPROVE:"APPROVE",REPORT:"REPORT",NO_INLINE:"NO_INLINE"});f["default"]=a}),66);
__d("getUnwrappedFbt",["FbtResultGK"],(function(a,b,c,d,e,f){function a(a){a=a.contents;var c=b("FbtResultGK").inlineMode,d=b("FbtResultGK").shouldReturnFbtResult;if(!d&&c!=="REPORT")return(a==null?void 0:a.length)===1&&typeof a[0]==="string"?a[0]:a}e.exports=a}),null);
__d("getFbtResult",["FbtResult","FbtResultGK","InlineFbtResult","getUnwrappedFbt","gkx","recoverableViolation"],(function(a,b,c,d,e,f,g){if(c("gkx")("20935")&&c("FbtResultGK").inlineMode==="TRANSLATION"){c("recoverableViolation")("TransAppInlineMode=TRANSLATION should not happen on Comet yet. "+("[inlineMode="+((b=c("FbtResultGK").inlineMode)!=null?b:"")+"]")+("[runtime_site_is_comet="+String(c("gkx")("20935"))+"]"),"internationalization")}function a(a){var b=c("getUnwrappedFbt")(a);if(b!=null)return b;b=a.contents;var d=a.patternString,e=a.patternHash;return c("FbtResultGK").inlineMode!=null&&c("FbtResultGK").inlineMode!=="NO_INLINE"?new(c("InlineFbtResult"))(b,c("FbtResultGK").inlineMode,d,e):c("FbtResult").get(a)}g["default"]=a}),98);
__d("warningComet",["SiteData","cr:1072546","cr:1072547","cr:1072549","cr:983844","err","fb-error"],(function(a,b,c,d,e,f,g){function a(a,b){return!1}b=a;c=b;g["default"]=c}),98);
__d("warningWWW",["WebDriverConfig","cr:1105154","cr:11202","cr:2682"],(function(a,b,c,d,e,f,g){a=b("cr:2682");c=a;g["default"]=c}),98);/*FB_PKG_DELIM*/
/**
 * License: https://www.facebook.com/legal/license/V9vdYColc4k/
 */
__d("react-0.0.0",["React"],(function(a,b,c,d,e,f){"use strict";function a(a){return a&&typeof a==="object"&&"default"in a?a["default"]:a}var g=a(b("React"));d={};var h={exports:d};function i(){h.exports=g}var j=!1;function k(){j||(j=!0,i());return h.exports}function c(a){switch(a){case void 0:return k()}}e.exports=c}),null);
__d("react",["react-0.0.0"],(function(a,b,c,d,e,f){e.exports=b("react-0.0.0")()}),null);